name: tornet_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  http: ^1.2.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/ChakraPetch-Light.ttf
          weight: 300
        - asset: assets/fonts/ChakraPetch-Regular.ttf
          weight: 400
        - asset: assets/fonts/ChakraPetch-Medium.ttf
          weight: 500
        - asset: assets/fonts/ChakraPetch-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ChakraPetch-Bold.ttf
          weight: 700    
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
